### ISSUE TITLE
Using the camera only - simple code examples

### ISSUE THREAD

**Issue by lorenzoromagnoli** [interactionresearchstudio/TaskCam_Arduino#1]
I tried to modify the complete code example you provided to control the camera only. 
I think I grabbed the right pieces of code from your sketch, but still, the camera doesn't seem able to save the pictures to the SD card. 

Some more documentation on how the camera, the SD card and the Arduino talk to each other would be really appreciated. 

Here is my code. 

```C
#include <SoftwareSerial.h>
#include <SPI.h>
#include <Wire.h>

#define CAM_RX  12
#define CAM_TX  13
#define CAM_PWR 10


SoftwareSerial camSerial(CAM_RX, CAM_TX); // RX, TX

int photoIndex=0;

void setup() {
  camSerial.begin(38400);
  Serial.begin(9600);
  initialiseCamera();

  digitalWrite(CAM_PWR, 0);

}

void loop() {
  // put your main code here, to run repeatedly:
  capturePicture();
  delay(5000);
}

// Initialise camera module (blocking)
void initialiseCamera() {
  camSerial.write('~');
  camSerial.write('i');
  camSerial.write(0x0D);
  camSerial.write(0x0A);

  delay(100);

  while (camSerial.available() < 2) {
    // Wait for "INI"
  }

#ifdef DEBUG
  Serial.println(F("Cam init'd"));
#endif

  // Flush serial
  while (camSerial.available() > 0) {
    camSerial.read();
  }
}


// Capture picture
void capturePicture() {
  digitalWrite(CAM_PWR, 1);
  
  // Flush serial
  while (camSerial.available() > 0) {
    camSerial.read();
  }

  // Send "Take photo" command to camera module
  camSerial.write(0x21);
  camSerial.write((uint8_t)photoIndex++);
  camSerial.write(0x0D);
  camSerial.write(0x0A);
  delay(1400);

  // Wait for saving to complete
  Serial.print("saving");
  while (camSerial.available() <= 0) {
    Serial.print(".");
  }
  Serial.println();

  // Flush serial
  while (camSerial.available() > 0) {
    camSerial.read();
  }

  digitalWrite(CAM_PWR, 0);

}
```

**Comment by mikevanis** [comment]
Yes, documentation on the camera module's inner workings is a little sparse at the moment. We'll look into beefing that up. As for your issue, try to wait a little for the camera module to turn on. Also, `initialiseCamera` and `indexQuestions` need to be called after the camera module is turned on. The whole camera module is powered off when CAM_PWR is pulled low, so when it's turned back on, it needs to be reinitialised. `indexQuestions` finds and counts all the questions in the SD card. 

Example sequence of turning the camera on: 

    digitalWrite(CAM_PWR, HIGH);
    delay(400);
    initialiseCamera();
    delay(200);
    indexQuestions();
    delay(800);
    // Now take photo.

You can, of course, keep the camera module on if a delay of 1.4 seconds is unsuitable for your application! We're doing some very conservative power saving on the default sketch so that the TaskCam can last on two AAs for the duration of a user study!

Let us know if you need more help :)

**Comment by lorenzoromagnoli** [comment]
Thanks @mikevanis for the quick reply!

By initializing the camera after turning it on every time I managed to shoot some pictures. ❤️ 

Here is my code:

```C
#include <SoftwareSerial.h>
#include <SPI.h>
#include <Wire.h>

#define CAM_RX  12
#define CAM_TX  13
#define CAM_PWR 10


SoftwareSerial camSerial(CAM_RX, CAM_TX); // RX, TX

int photoIndex=0;

void setup() {
  camSerial.begin(38400);
  Serial.begin(9600);
  initialiseCamera();
  digitalWrite(CAM_PWR, 0);
}

void loop() {
  // put your main code here, to run repeatedly:
	digitalWrite(CAM_PWR, HIGH);
	initialiseCamera();
  capturePicture();
	digitalWrite(CAM_PWR, LOW);
  delay(5000);
}

// Initialise camera module (blocking)
void initialiseCamera() {
  camSerial.write('~');
  camSerial.write('i');
  camSerial.write(0x0D);
  camSerial.write(0x0A);

  delay(100);

  while (camSerial.available() < 2) {
    // Wait for "INI"
  }

#ifdef DEBUG
  Serial.println(F("Cam init'd"));
#endif

  // Flush serial
  while (camSerial.available() > 0) {
    camSerial.read();
  }
}


// Capture picture
void capturePicture() {

  // Flush serial
  while (camSerial.available() > 0) {
    camSerial.read();
  }

  // Send "Take photo" command to camera module
  camSerial.write(0x21);
  camSerial.write((uint8_t)photoIndex++);
  camSerial.write(0x0D);
  camSerial.write(0x0A);
  delay(1400);

  // Wait for saving to complete
  Serial.print("saving");
  while (camSerial.available() <= 0) {
    Serial.print(".");
  }
  Serial.println();

  // Flush serial
  while (camSerial.available() > 0) {
    camSerial.read();
  }
}

```
There are still a couple of things which are not very clear: 
- Why should I call `indexQuestions()` if I'm not interested in reading those?
- I see that the files by default get numbered: Q[a number I send to the camera via serial]-00; at the moment I'm manually incrementing the Q index by doing this `camSerial.write((uint8_t)photoIndex++);` but I wonder, is there any way to pass to the camera a custom name for the file? 
- is there a API to get the number of photos currently saved on the camera?

Thanks for helping out, I'd like to give this camera to my students, and ask them to use it in combination with sensors, and I need to hack the code a little bit for that.

**Comment by mikevanis** [comment]
I guess the answer to all of your questions is to do with the fact that the camera is really geared up for taking pictures in order to answer questions displayed on the TaskCam's screen, so the Serial API is as lean and simple as possible to facilitate that. When you take a picture, the camera module saves it into the SD card with the question number first, and then an auto-incrementing index (if it's been answered more than once). It then goes inside the questions text file and marks it as answered by inserting a marker at the beginning of the question. In order to do all of the question marking, it needs to know where the carriage returns are inside the q.txt file - that's what `indexQuestions` does. You could try to take a photo without calling `indexQuestions` first, but I can't remember off the top of my head if it'll work or not! 

Unfortunately I don't think there is a way to get the number of photos saved at this moment. However, I may be wrong, so we'll need to wait for the camera wizard, @andysheen to confirm.

If you're interested in the camera module itself, it's much more complicated than Arduino as it's programmed in ChibiOS. However, all the code is on GitHub [here] (https://github.com/interactionresearchstudio/STM32_DCMI_CAMERA). If you'd like to reprogram the camera module to add functionality, you'll need to use an STLINK programmer or similar. I'll close this issue for now, but please get in touch about what you're doing with the TaskCams, we'd love to see what you're up to and are super curious!
